=begin
#ARTIK Cloud API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ArtikCloud::DevicesSharesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DevicesSharesApi' do
  before do
    # run before each test
    @instance = ArtikCloud::DevicesSharesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DevicesSharesApi' do
    it 'should create an instact of DevicesSharesApi' do
      expect(@instance).to be_instance_of(ArtikCloud::DevicesSharesApi)
    end
  end

  # unit tests for create_share_for_device
  # Share a device 
  # Share a device 
  # @param device_id Device ID.
  # @param device_share_info Device object that needs to be added
  # @param [Hash] opts the optional parameters
  # @return [DeviceSharingId]
  describe 'create_share_for_device test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_sharing_for_device
  # Delete specific share of the given device id
  # Delete specific share of the given device id
  # @param device_id Device ID.
  # @param share_id Share ID.
  # @param [Hash] opts the optional parameters
  # @return [DeviceSharingId]
  describe 'delete_sharing_for_device test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_all_shares_for_device
  # List all shares for the given device id
  # List all shares for the given device id
  # @param device_id Device ID.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :count Desired count of items in the result set.
  # @option opts [Integer] :offset Offset for pagination.
  # @return [DeviceSharingEnvelope]
  describe 'get_all_shares_for_device test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sharing_for_device
  # Get specific share of the given device id
  # Get specific share of the given device id
  # @param device_id Device ID.
  # @param share_id Share ID.
  # @param [Hash] opts the optional parameters
  # @return [DeviceSharing]
  describe 'get_sharing_for_device test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
