=begin
#ARTIK Cloud API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ArtikCloud::DevicesStatusApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DevicesStatusApi' do
  before do
    # run before each test
    @instance = ArtikCloud::DevicesStatusApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DevicesStatusApi' do
    it 'should create an instact of DevicesStatusApi' do
      expect(@instance).to be_instance_of(ArtikCloud::DevicesStatusApi)
    end
  end

  # unit tests for get_device_status
  # Get Device Status
  # Get Device Status
  # @param device_id Device ID.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :include_snapshot Include device snapshot into the response
  # @option opts [BOOLEAN] :include_snapshot_timestamp Include device snapshot timestamp into the response
  # @return [DeviceStatus]
  describe 'get_device_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_devices_status
  # Get Devices Status
  # Get Devices Status
  # @param dids List of device ids (comma-separated) for which the statuses are requested.
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :include_snapshot Include device snapshot into the response
  # @option opts [BOOLEAN] :include_snapshot_timestamp Include device snapshot timestamp into the response
  # @return [DeviceStatusBatch]
  describe 'get_devices_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_device_status
  # Update Device Status
  # Update Device Status
  # @param device_id Device ID.
  # @param [Hash] opts the optional parameters
  # @option opts [DeviceStatusPut] :body Body
  # @return [DeviceStatus]
  describe 'put_device_status test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
