=begin
Artik Cloud API

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

License: MIT
http://en.wikipedia.org/wiki/MIT_License

Terms of Service: http://www.samsung.com/global/business/mobile/info/terms-and-conditions.html

=end

require 'spec_helper'
require 'json'

# Unit tests for ArtikCloud::TokensApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TokensApi' do
  before do
    # run before each test
  let(:instance) { ArtikCloud::TokensApi.new(API_CLIENT) }
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokensApi' do
    it 'should create an instact of TokensApi' do
      expect(@instance).to be_instance_of(ArtikCloud::TokensApi)
    end
  end

  # unit tests for check_token
  # Check Token
  # (Deprecated) Check Token. See tokenInfo
  # @param token_info Token object to be checked
  # @param [Hash] opts the optional parameters
  # @return [CheckTokenResponse]
  describe 'check_token test' do
    it "should work" do
      response = instance.token_info
      expect(response).to be_a(ArtikCloud::TokenInfoSuccessResponse)
      expect(response.data.expires_in).to_not be_nil
    end
  end

  describe 'refresh_token test' do
    it "should work" do
      pending 'refresh_token is invalid, a good one is needed'
      refresh_token = "bb90333aee114b3e97284814d978080d"

      response = instance.refresh_token("refresh_token", refresh_token)
      response.should be_a(ArtikCloud::RefreshTokenResponse)
    end
  end
end
