=begin
#ARTIK Cloud API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for ArtikCloud::TokensApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TokensApi' do
  before do
    # run before each test
    @instance = ArtikCloud::TokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TokensApi' do
    it 'should create an instact of TokensApi' do
      expect(@instance).to be_instance_of(ArtikCloud::TokensApi)
    end
  end

  # unit tests for check_token
  # Check Token
  # (Deprecated) Check Token. See tokenInfo
  # @param token_info Token object to be checked
  # @param [Hash] opts the optional parameters
  # @return [CheckTokenResponse]
  describe 'check_token test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for refresh_token
  # Refresh Token
  # Refresh Token
  # @param grant_type Grant Type.
  # @param refresh_token Refresh Token.
  # @param [Hash] opts the optional parameters
  # @return [RefreshTokenResponse]
  describe 'refresh_token test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for token_info
  # Token Info
  # Returns the Token Information
  # @param [Hash] opts the optional parameters
  # @return [TokenInfoSuccessResponse]
  describe 'token_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
